language: node_js
node_js:
    - "7"
script:
    - echo "Deploy!!"
install: 
    - npm install -g firebase-tools
after_success:
    - firebase deploy --project relier-f998f --token 0h2iU7n7Bx-a4CgYIARAAGBESNwF-L9IraxixJ13D4sPMDeC1UV_pT35d6x-zqlJ79S56UlsY3aWbP_cRbeYZBJMIInjg_m-5Px4